name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
        description: prod or dev

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: ci-cd
        run: echo 'start ci-cd'
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - name: deploy
        run: echo 'start deploy'
