name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
        description: prod or dev

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: deploy
        run: echo 'start deploy'
