name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
        description: prod or stg or dev

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: ci-cd
        run: echo 'start ci-cd'
  ci2:
    runs-on: ubuntu-latest
    if: ${{inputs.environment}} == ('stg' || 'prod')
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: ci-cd2
        run: echo 'start ci-cd2'
      - name: run
        if: ${{inputs.environment}} == ('stg' || 'prod')
        run: echo ${{inputs.environment}}
    needs: ci
  ci3:
    runs-on: ubuntu-latest
    steps:
      - name: ci-cd3
        run: echo 'start ci-cd3'
    needs: ci2
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: deploy
        run: echo 'start deploy'
    needs: ci3
