name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
        description: prod or dev

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: ci-cd
        run: echo 'start ci-cd'
  ci2:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: ci-cd2
        run: echo 'start ci-cd2'
    needs: ci
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: deploy
        run: echo 'start deploy'
    needs: ci2
